#!/usr/bin/env bash

LOCALES=(
  pt_BR
  en_US
  pt_PT
)
set -eu -o pipefail

xgettext -d ritm_annotation -o ritm_annotation/i18n/ritm_annotation.pot --files-from=<(find ritm_annotation -name '*.py'; python -c 'import argparse; print(argparse.__file__)')
sed -i 's;CHARSET;UTF-8;g' ritm_annotation/i18n/ritm_annotation.pot

for LOCALE in "${LOCALES[@]}"; do
  mkdir -p ritm_annotation/i18n/"$LOCALE"
  if [[ ! -f ritm_annotation/i18n/$LOCALE/LC_MESSAGES/ritm_annotation.po ]]; then
    msginit -i ritm_annotation/i18n/ritm_annotation.pot -o  ritm_annotation/i18n/"$LOCALE"/LC_MESSAGES/ritm_annotation.po 
  fi
  msgmerge --no-fuzzy-matching -U itm_annotation/i18n/"$LOCALE"/LC_MESSAGES/ritm_annotation.po ritm_annotation/i18n/ritm_annotation.pot
  msgfmt -o ritm_annotation/i18n/"$LOCALE"/LC_MESSAGES/ritm_annotation.mo ritm_annotation/i18n/"$LOCALE"/LC_MESSAGES/ritm_annotation.po
done
